### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by shanealanevans** [eiriniar/CellCnn#10]
Traceback (most recent call last):
  File "/Users/shane/Documents/tools/CellCnn/cellCnn/run_analysis.py", line 242, in <module>
    main()
  File "/Users/shane/Documents/tools/CellCnn/cellCnn/run_analysis.py", line 185, in main
    outdir=args.outdir)
  File "/Users/shane/Documents/tools/CellCnn/cellCnn/model.py", line 167, in fit
    accur_thres=self.accur_thres, verbose=self.verbose)
  File "/Users/shane/Documents/tools/CellCnn/cellCnn/model.py", line 484, in train_model
    w_best_net = keras_param_vector(best_net)
  File "/Users/shane/Documents/tools/CellCnn/cellCnn/utils.py", line 117, in keras_param_vector
    W_tot = np.hstack([W.T, b.reshape(-1, 1), W_out])
  File "<__array_function__ internals>", line 6, in hstack
  File "/Users/shane/.local/share/virtualenvs/CellCnn-MbiXJHLq/lib/python3.7/site-packages/numpy/core/shape_base.py", line 344, in hstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

**Comment by shanealanevans** [comment]
This happened when I tried to run the pipwline, it ran and generated about 14 different output files, but then errored out with this message.
